### ISSUE TITLE
[FR] Expose option to load custom languages for shiki

### ISSUE THREAD

**Issue by mProjectsCode** [expressive-code/expressive-code#106]
I would like to use Expressive Code in my starlight project, especially since starlight now ships with it enabled by default, but I found no way to register custom tmlanguages for shiki for Expressive Code. And since starlight fails to render a page with expressive code enabled if there exists a code block of a language that is unknown to shiki, I sadly can't use Expressive Code in my project.

This FR is a 2-in-1 package

1. I would like to be able to register custom tmlanguages to shiki used by expressive code
2. Expressive code should fall back to no highlighting (and not error) for a code block where shiki does not have a tmlanguage for the code block language (idk if this is a starlight issue, the starlight people directed me to this repo)

For context: The error trace in starlight for a codeblock of a language that is unknown to shiki looks like this
![image](https://github.com/expressive-code/expressive-code/assets/61602848/e7ac8b33-0e53-40e4-8697-389f1145f784)

**Comment by hippotastic** [comment]
Thank you for this feature request!

I agree that a console warning and rendering as plain text would be the better way to handle unknown languages. Throwing an error is too harsh for this type of issue.

Regarding the custom language registration, I'm pasting some additional context here that was provided on Discord. You were using roughly the following configuration in Astro:

```js
import { defineConfig } from 'astro/config'
import { bundledLanguages } from 'shikiji'

const MetaBind = {
  // defined here: https://github.com/mProjectsCode/obsidian-meta-bind-plugin-docs/blob/master/metaBindLanguage.js
}

export default defineConfig({
  // ...
  markdown: {
    shikiConfig: {
      langs: [
        ...Object.keys(bundledLanguages),
        {
          id: 'meta-bind',
          scopeName: 'source.meta-bind',
          grammar: MetaBind,
          aliases: [],
        },
      ],
    },
  },
})
```

To fix this part of the issue, the `markdown.shikiConfig` config option must be recognized by `astro-expressive-code` and passed down to `@expressive-code/plugin-shiki`, which must then use the contained settings when creating the highlighter.

**Comment by mProjectsCode** [comment]
Regarding the config, I noticed that astro allows passing the grammar in a wrapper object like in the example in your message and passing the grammar directly, so like the following example.

```ts
import { defineConfig } from 'astro/config'
import { bundledLanguages } from 'shikiji'

const MetaBind = {
  // defined here: https://github.com/mProjectsCode/obsidian-meta-bind-plugin-docs/blob/master/metaBindLanguage.js
}

export default defineConfig({
  // ...
  markdown: {
    shikiConfig: {
      langs: [
        ...Object.keys(bundledLanguages),
        MetaBind
      ],
    },
  },
})
```

**Comment by hippotastic** [comment]
Custom language support has landed in version 0.30.0! :)

As described in my previous message, `astro-expressive-code` now automatically picks up Astro's `markdown.shikiConfig.langs` config option (if set) and forwards it to `plugin-shiki`. Alternatively, you can also set this option directly in Expressive Code's options (`shiki: { langs: [...] }`).

Please note that only the flattened Shikiji version of the `langs` array is supported, not the old Shiki version, as I didn't want to introduce the overhead of a conversion function for an option that's probably only used by a few selected people. :) So, passing the grammars directly without a wrapper object is the way to go.

I'll create a PR in the Starlight repo to bump the EC dependency to `^0.30.0`. If you want to use this feature within Starlight before the PR has been created and merged, you can use PNPM overrides to upgrade right away:

```diff
// package.json
{
  "name": "your-docs-repo",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro check && astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "@astrojs/starlight": "^0.13.1",
    "astro": "^3.6.4",
+   "astro-expressive-code": "^0.30.0",
    "sharp": "^0.32.6"
  },
+ "pnpm": {
+   "overrides": {
+     "astro-expressive-code": "^0.30.0"
+   }
+ }
}
```

After making these changes and running `pnpm i`, your Starlight project will use the latest `astro-expressive-code` version immediately.

Please let me know if you encounter any issues. Closing this as completed now.

**Comment by mProjectsCode** [comment]
I did the version override with npm since i don't use pnpm and it works great. Thanks for implementing this :)

**Comment by mProjectsCode** [comment]
The only thing I noticed is that the theme seems to be different.

Expressive code on
![image](https://github.com/expressive-code/expressive-code/assets/61602848/43c38507-d3a8-4356-a976-46e6dd78a312)
Expressive code off
![image](https://github.com/expressive-code/expressive-code/assets/61602848/cbebee28-6615-4da3-bcf8-8b36677f9910)

**Comment by hippotastic** [comment]
Great to hear that it works for you!

That Expressive Code's Starlight integration comes with a set of new default themes is expected behavior. The previous Starlight default theme was based on the `css-variables` Shiki theme which only supports very limited grammar rules. With Expressive Code enabled in Starlight, we were no longer limited to this approach, so we picked a new set of default themes and decided upon Night Owl & Light Owl by Sarah Drasner, a fairly popular set of themes.

**Comment by mProjectsCode** [comment]
Did some more tmlanguage trickery to get my language to run as part of the markdown language and now my docs look mostly the same as my plugin (which the docs are for) 🎉.

Docs:
![image](https://github.com/expressive-code/expressive-code/assets/61602848/72dfb742-3a38-4c93-bc96-7e6b785f994c)

My Plugin:
![image](https://github.com/expressive-code/expressive-code/assets/61602848/f567d264-4a60-44f4-8678-93918763752a)

**Comment by hippotastic** [comment]
Very nice! Can't wait to see it live!

**Comment by mProjectsCode** [comment]
[And it's live](https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/guides/buttons/) 🎉

**Comment by hippotastic** [comment]
Looks great! Very nice usage of the line & text highlighting as well, this really makes the examples easy to understand.
