### ISSUE TITLE
Feature: custom frames

### ISSUE THREAD

**Issue by tmcw** [expressive-code/expressive-code#107]
Hi! We're happily using expressive-code in [our docs](https://docs.val.town/). It's awesome, and makes everything look high-polish (even if we've got a ton of writing and copyediting to do 😆 )

For chunks of code, we're generally giving examples for the platform, and it'd be great to add a button to each code example that says like "Open in Val Town". I could imagine the same for other scenarios - open in CodePen, open in CodeSandbox, etc. Or even code with a built-in REPL.

It's be awesome if there was a way to provide a custom frame - like by providing our own method that returns HAST like this does internally for frames. I know that right now frame names are validated so that might make the 'check' step harder, though. But anyway - if this is potentially in scope it'd be awesome, and if you have an idea for how it could be implemented cleanly, we could help with a PR!

**Comment by hippotastic** [comment]
Hello and welcome!

Modifying the HAST of the code blocks at any stage is already possible with Expressive Code. In fact, this was one of the key design principles when developing this package with its plugin architecture. I'm just writing its documentation in Starlight and your request is a great proof that I need to include plugin development examples. :)

Here's a quick StackBlitz example on how you can add custom buttons by writing a small plugin:

https://stackblitz.com/edit/github-n7kyh4?file=src%2Fcontent%2Fdocs%2Findex.mdx,astro.config.mjs,plugins%2Fcustom-open-button.mjs

![image](https://github.com/expressive-code/expressive-code/assets/6137925/3bc6c5e3-0e4d-4dae-90d3-deded01716d6)

You can find my existing documentation on how to write plugins (including all the available hooks and data) here: https://github.com/expressive-code/expressive-code/blob/main/packages/%40expressive-code/core/README.md#writing-your-own-plugins

Hope that helps! Please let me know if you run into any issues.
