### ISSUE TITLE
Feature req: Collapse to frame title

### ISSUE THREAD

**Issue by joshka** [expressive-code/expressive-code#109]
I'm writing a docs site in which having some code blocks that show an entire code file is a useful thing, but I don't want these to be shown in full by default. I can surround these with details/summary tags to make these collapsed, but I think it might be neat to have this built in to the frame plugin so you can just see the title of the code block when collapsed.

Is this something that would be easy to achieve?

**Comment by joshka** [comment]
Yes - that's perfect.
I think as a plugin it probably needs to render some text / an arrow inside the frame title, but that code will work fine for my our needs as-is. Thanks so much!

**Comment by hippotastic** [comment]
Agreed, the collapse UI can be improved for sure. The plugin was just meant as an example to show how you can implement a feature like this using the plugin API. Feel free to adapt it to your own needs.

I love to hear that it works well for you. Happy coding!
