### ISSUE TITLE
Unnecessary tab index on pre elements?

### ISSUE THREAD

**Issue by fflaten** [expressive-code/expressive-code#123]
The audit feature in Astro dev toolbar says `tabindex=0` doesn't belong on the `<pre>`-elements. Thoughts?
![image](https://github.com/expressive-code/expressive-code/assets/3436158/08870dd4-dad9-430d-9907-20652524247e)

Do we need it to be focusable or is the copy button enough? Doesn't look like CTRL+C works on `<pre>` focus either way. Any other benefits? Relevant if scrollable maybe?

**Comment by hippotastic** [comment]
The attribute is intentional. According to our a11y testing, the attribute is required for screen readers to properly read the code. The warning is therefore incorrect and can be ignored.

**Comment by fflaten** [comment]
Thanks for the quick response. Found a [relevant discussion](https://github.com/withastro/astro/pull/9170#discussion_r1413851042) for reference 🙂 
IMO the rule should be fixed.

**Comment by hippotastic** [comment]
Thank you for linking this! I wanted to look it up as well and didn't find it quickly. :) Here's another one that I remember as well: https://github.com/withastro/astro/issues/8001

I'm not sure if we can do anything to avoid that supposedly incorrect flagging of the attribute by the toolbar. If more users report this in the future, we might need to investigate further.

**Comment by davidysoards** [comment]
The audit appears to be smart enough that it doesn't flag elements with overflow (and therefore a scrollbar).
