### ISSUE TITLE
How to change the copy button text?

### ISSUE THREAD

**Issue by liuhq** [expressive-code/expressive-code#130]
how can I modify the inner text of the copy button(tips, copied...)?

this

![image](https://github.com/expressive-code/expressive-code/assets/48037182/a915df0e-b56a-49f0-86a8-8b3462d680f7)

and

![image](https://github.com/expressive-code/expressive-code/assets/48037182/a3b9825d-57dc-4011-bf48-9c848989de23)

**Comment by hippotastic** [comment]
Hello! Sorry about that, I forgot to add this to the documentation. Will add it!

Here's how it works. In your config file (e.g. `astro.config.mjs`), you add the following:
```js
import { pluginFramesTexts } from '@expressive-code/plugin-frames'

// This is how you override the texts of an existing language:
pluginFramesTexts.overrideTexts('en', {
  terminalWindowFallbackTitle: 'My terminal window',
  copyButtonTooltip: 'My copy to clipboard tooltip',
  copyButtonCopied: 'My copied text!',
})

// This is how you add translations for a new language locale
// (note that "de" is already present, this just shows how it works):
pluginFramesTexts.addLocale('de', {
  terminalWindowFallbackTitle: 'Terminal-Fenster',
  copyButtonTooltip: 'In die Zwischenablage kopieren',
  copyButtonCopied: 'Kopiert!',
})
```

**Comment by hippotastic** [comment]
Another note: If you are a Starlight user, you can use Starlight's own i18n files as documented here: https://starlight.astro.build/guides/i18n/#translate-starlights-ui

**Comment by liuhq** [comment]
> Hello! Sorry about that, I forgot to add this to the documentation. Will add it!
> 
> Here's how it works. In your config file (e.g. `astro.config.mjs`), you add the following:
> 
> ```js
> import { pluginFramesTexts } from '@expressive-code/plugin-frames'
> 
> // This is how you override the texts of an existing language:
> pluginFramesTexts.overrideTexts('en', {
>   terminalWindowFallbackTitle: 'My terminal window',
>   copyButtonTooltip: 'My copy to clipboard tooltip',
>   copyButtonCopied: 'My copied text!',
> })
> 
> // This is how you add translations for a new language locale
> // (note that "de" is already present, this just shows how it works):
> pluginFramesTexts.addLocale('de', {
>   terminalWindowFallbackTitle: 'Terminal-Fenster',
>   copyButtonTooltip: 'In die Zwischenablage kopieren',
>   copyButtonCopied: 'Kopiert!',
> })
> ```
> 
> If your package manager is strict about the dependencies and does not allow importing `@expressive-code/plugin-frames` right away, you may need to add `@expressive-code/plugin-frames` as a dependency to your project.

Thank you very much! It worked fine.
