### ISSUE TITLE
Docs: Missing demo and examples

### ISSUE THREAD

**Issue by krzkaczor** [expressive-code/expressive-code#143]
This project looks great but docs desperately need examples/demo section. I get that you use `expressive-code` in the docs so it's kinda a demo but I would love to see a dedicated showcase of what's possible.

**Comment by krzkaczor** [comment]
@hippotastic Yes, the text markers subpage looks great. The only problem is that it's buried in docs and as a user who just learned about your lib, I don't want to scroll through multiple subpages only to see what's possible. 

I simply suggest creating a "demo" or "examples" page showcasing the most advanced features.

**Comment by hippotastic** [comment]
Gotcha, good idea! This would probably serve as a good introduction page, which I'm currently missing. I'll try to come up with something along these lines.

Thanks for your input!
