### ISSUE TITLE
Specific line numbers ( different 

### ISSUE THREAD

**Issue by geerew** [expressive-code/expressive-code#161]
Hey have you thought about allowing targeted line numbers? 

Something like this?

<img width="989" alt="Screenshot 2024-02-22 at 14 13 14" src="https://github.com/expressive-code/expressive-code/assets/494875/e00ca679-819c-4dd5-849d-8d71160208b5">

I think this would be a great addition and make it easier to go into further detail. 

I know you can turn on line numbers and reference that but a) someone might not want to turn on line number or b) if line numbers are enabled they don't catch the eye

**Comment by hippotastic** [comment]
Would the labels feature solve your use case? https://expressive-code.com/key-features/text-markers/#adding-labels-to-line-markers

**Comment by geerew** [comment]
oo it sure does. I didn't realise you could do that with `text-markers`. I guess im using an older version of expressive code! 

Thank you for an amazing repo
