### ISSUE TITLE
Use the product on your home page

### ISSUE THREAD

**Issue by muddylemon** [expressive-code/expressive-code#168]
Not a bug - more of a suggestion - on your home page there's an abstract illustration of highlighted code, but why not just put a snippet of code somewhere on there? That's what I looked for when I hit your landing page and didn't find. 

Looks nice tho :)

**Comment by hippotastic** [comment]
That's a very good suggestion, I've also had the feeling that the home page is missing something.

I'll update it and add 1-2 code blocks showing off all the features in use. Maybe even clickable so that you can quickly get to the relevant page explaining the clicked feature.

Thank you! :)
