### ISSUE TITLE
No way to disable selection and scrollbar styling

### ISSUE THREAD

**Issue by Princesseuh** [expressive-code/expressive-code#18]
Some themes changes the color and background-color of the selection, like such:

<img width="414" alt="image" src="https://github.com/expressive-code/expressive-code/assets/3019731/d9b9d9ac-f864-4130-8fec-40ef03ccf1cf">

and the color of the scrollbar:

<img width="781" alt="image" src="https://github.com/expressive-code/expressive-code/assets/3019731/da98a954-9b67-4aee-b519-92cda8698ae2">

While this is definitely a desirable behaviour, I would like to be able to disable this, as I prefer letting the user's operating system and browser theme those.

It's currently possible to change the color of all those elements, using settings such as `codeSelectionBackground`, however it seems like it's not possible to set it to use the default behaviour (`initial` result in the wrong behaviour). Ideally, I would love to be able to do for example, something like `codeSelectionBackground: false` to completely remove the style definition for selection, same thing for scrollbar.

**Comment by hippotastic** [comment]
Hello @Princesseuh, glad to have you here as well! Thank you for submitting this issue.

I agree that being able to disable the themed scrollbars and text selection is a good option to have, so I support adding this feature to Expressive Code.

Unfortunately, as you have also pointed out, there doesn't seem to be a proper well-supported CSS value to use the default styling/colors, so I need to add this to the configuration options somehow. 

As all other styleOverrides are strings (or resolve to strings), and as I don't want to add any unexpected "special" string values or the possibility to use `undefined`, `null` or `false` for only some of these overrides, I would solve this by adding the following new top-level config options:

- `useThemedScrollbars?: boolean | undefined`
   > Whether the theme is allowed to style the scrollbars. Defaults to `true`.
   > 
   > If set to `false`, scrollbars will be rendered using the browser's default style.
   > 
   >  Note that you can override the individual scrollbar colors defined by the theme using the `styleOverrides` option.

- `useThemedSelectionColors?: boolean | undefined`
  > Whether the theme is allowed to style selected text. Defaults to `true`.
  > 
  > If set to `false`, selected text will be rendered using the browser's default style.
  > 
  > Note that you can override the individual selection colors defined by the theme
using the `styleOverrides` option.

Do you think this would solve your issue?

**Comment by Princesseuh** [comment]
That seems like a good way to solve this! I think it's the most intuitive considering what you outlined

**Comment by hippotastic** [comment]
Both options are available in the latest release now. 😊 After updating your dependencies, you should be able to use them right now:

```
🦋  success packages published successfully:
🦋  @expressive-code/core@0.11.0
🦋  @expressive-code/plugin-frames@0.10.2
🦋  @expressive-code/plugin-shiki@0.3.9
🦋  @expressive-code/plugin-text-markers@0.2.11
🦋  astro-expressive-code@0.13.0
🦋  expressive-code@0.13.0
🦋  remark-expressive-code@0.13.0
```

Please let me know if it works for you!

**Comment by Princesseuh** [comment]
It works perfectly, amazing work! Thank you very much for the quick answer and update!
