### ISSUE TITLE
Marker labels can't include backslash

### ISSUE THREAD

**Issue by stancl** [expressive-code/expressive-code#197]
Hey! I'm trying to use a `{"marker label": 1-2}` that includes a `\` but seems like they always get stripped no matter how they're formatted? I tried `\\` (even `\\\` and `\\\\`) in both `''` and `""` strings but seems like EC always strips them out.

Thanks!

**Comment by hippotastic** [comment]
Thank you for reporting this! I have fixed the issue in version 0.35.2, which I just released to NPM. In MDX files, `\\` should be enough now to get a backslash in the output. In MD files, even `\` should work.

**Comment by stancl** [comment]
Thanks a lot for the quick fix!
