### ISSUE TITLE
`plugin-frames` does not process file name comments that include `+` in the file name

### ISSUE THREAD

**Issue by amandaguthrie** [expressive-code/expressive-code#204]
`plugin-frames` version: `0.35.2`

SvelteKit files are regularly prefixed with `+` in the file name, like `+layout.svelte` and `+page.server.ts`. Commented file names that include a `+` are not processing as titles.

`+` is a supported character for file paths on Linux, Windows, and other major operating systems.

`+` is not included in the file name regex in `utils/getFileCommentRegExpString`.

Pull request: #205

**Comment by hippotastic** [comment]
Wow, this is great! Thank you very much for this well-described issue AND the accompanying fix PR!

**Comment by hippotastic** [comment]
I just released your fix as version 0.35.3 on NPM. Thanks again!
