### ISSUE TITLE
question on collapse. Is it expected that code gets collapsed if lines is greater than 16 lines? Can this default be turned off?

### ISSUE THREAD

**Issue by chardskarth** [expressive-code/expressive-code#212]

**Comment by hippotastic** [comment]
Hello! There is no such default, it does not collapse any lines unless you tell it to.

You can find the docs on how to use the collapse plugin here: https://expressive-code.com/plugins/collapsible-sections/#usage-in-markdown--mdx

**Comment by chardskarth** [comment]
Oh right. There's no such default. I overlooked [a config that's being set by an astro template](https://github.com/cirry/astro-yi/blob/00c4510b354fbff5f75e37c1bcbc31df349c5ac4/README.md?plain=1#L93) that I'm using. 
Closing now. Thanks!
