### ISSUE TITLE
How can support two languages at once

### ISSUE THREAD

**Issue by patrick91** [expressive-code/expressive-code#213]
This is a bit of weird request, but on our site we use a custom rehype plugin to parse codeblocks that have a `+` in their language and if so, we create two code blocks side by side, like this:

![CleanShot 2024-06-04 at 11 15 13@2x](https://github.com/expressive-code/expressive-code/assets/667029/22facf62-abe3-4d5d-8e1c-6207a6f5ef44)

I've tried with adding a rehype plugin to Astro's MDX, but it seems to be breaking the integration, probably because it runs after Expressive Code?

**Comment by hippotastic** [comment]
Hello! I'd recommend creating a custom `.astro` component wrapper for this that applies a multi-column grid style to its contents through CSS. You could then use it like this from MDX:

````mdx
import CodeGrid from './components/CodeGrid.astro'

<CodeGrid>
```json
{
  "hello": true
}
```

```json
{
  "data": null,
  "errors": []
}
```
</CodeGrid>
````

**Comment by patrick91** [comment]
@hippotastic I might do that, thanks! I wanted to avoid having to update the docs, but it's probably better than having a ugly plugin :D

**Comment by patrick91** [comment]
that worked well! I'll close the issue 😊
