### ISSUE TITLE
Demo using different themes

### ISSUE THREAD

**Issue by jav-ed** [expressive-code/expressive-code#215]
First of all, thank you for this great work. I like the project quite a bit. So, if the maintainer don't mind, I would like to showcase a short demo. Just in case, anyone would like to see within a few seconds at least one feature, that is, the theming feature.

https://github.com/expressive-code/expressive-code/assets/47569896/efc42247-ad10-44f0-8f2d-d0a4c1e46884

**Comment by hippotastic** [comment]
Hey @jav-ed, welcome! Thank you very much the praise and your idea of showcasing features. I love it, thanks for investing time into this!

If it fits your plans with these videos (and only then; no pressure!) I could even imagine linking to such videos from my docs if they are concise and fit the topic, allowing users to quickly see what is possible with a particular feature.

**Comment by jav-ed** [comment]
@hippotastic Thank you for the fast reply. Also, a bonus is that the response is so positive.

At the moment, I had no plans to do demos or tutorials on Expressive Code. However, I will, inshallah, use this tool quite a bit.

My current plan is to, inshallah, finish my webpage. On this webpage, I would like, among other things, to teach how to code in Python. After this experience, I might be even somewhat qualified to give tutorials or demos on Expressive Code.

To wrap it up, I would love to tell people about this great repo. However, to be very clear, I can give no guarantees at the moment if I will be able to do it. Also, I think I did not fully understand your requirements.

Do you want to see demos or tutorials?

**Comment by hippotastic** [comment]
Thank you for your response! I think I just misunderstood the purpose of your initial post and thought you were asking me if I'd be interested in having some kind of video showcase. I didn't want to cause you any extra efforts, so please ignore my questions. :) 

It's perfectly fine to include EC in any videos you create, and there is no need to ask beforehand. Happy coding and good luck with your website!
