### ISSUE TITLE
When I upgrade Starlight, the style is lost. how to solve this problem?

### ISSUE THREAD

**Issue by moatkon** [expressive-code/expressive-code#217]
normal:
![image](https://github.com/expressive-code/expressive-code/assets/150421704/f5898f1a-68e4-4432-8412-16bea2900cbd)

When I upgrade Starlight, the style is lost:
![image](https://github.com/expressive-code/expressive-code/assets/150421704/74698fc9-d2aa-428a-ae68-f6dba0f37864)

![image](https://github.com/expressive-code/expressive-code/assets/150421704/c30eb46e-f919-4b92-ac76-f2f18fe86a01)

**Comment by moatkon** [comment]
use 
`npx @astrojs/upgrade` 
to upgrade

**Comment by hippotastic** [comment]
Hello! Thank you for reporting this.

I have just attempted to reproduce this by upgrading my Starlight-based docs site to the latest Astro & Starlight versions using the `@astrojs/upgrade` command. I ended up with the exact same versions that you also have in your screenshot. However, everything keeps working fine on my end. All the styles continue to work, both in build and dev mode. (I noticed a new Vite warning about `emitFile` though which I will fix. But this does not cause styles to go missing.)

Could you please either share your repo in case it's public, or at least the full contents of your `package.json`, Astro config and EC config (in case you have it in a separate file)?

**Comment by moatkon** [comment]
I have solved the problem, and I modified the version in Package.json

old:
  "dependencies": {
    "@astrojs/react": "^3.0.10",
    "@astrojs/starlight": "^0.21.5",
    "@types/react": "^18.2.58",
    "@types/react-dom": "^18.2.19",
    "astro": "^4.5.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "starlight-image-zoom": "^0.4.0",
    "starlight-view-modes": "^0.5.3"
  }

new：
  "dependencies": {
    "@astrojs/check": "^0.7.0",
    "@astrojs/react": "^3.5.0",
    "@astrojs/starlight": "^0.24.2",
    "astro": "^4.10.2",
    "starlight-image-zoom": "^0.5.0",
    "starlight-view-modes": "^0.5.3",
    "typescript": "^5.4.5"
  }
