### ISSUE TITLE
Set responsive font-size

### ISSUE THREAD

**Issue by nemanjam** [expressive-code/expressive-code#220]
I want default `font-size: 14px` and `font-size: 16px` above the `lg` Tailwind breakpoint, I found in the docs `codeFontSize` style override option but how to pass media query for the breakpoint, I can't find any info in the docs?

https://expressive-code.com/reference/style-overrides/#codefontsize

**Comment by hippotastic** [comment]
Hello! I'd suggest defining a custom CSS variable in your site-wide CSS, which can make full use of any media queries. You can then pass `var(--your-font-size-variable)` to the `codeFontSize` option.

**Comment by nemanjam** [comment]
Ok, thank you.
