### ISSUE TITLE
`astro check` warning that `vite-plugin-astro-expressive-code` "is likely not vite-compatible"

### ISSUE THREAD

**Issue by evadecker** [expressive-code/expressive-code#221]
Recently a warning began appearing in the terminal when running `astro check`:

```
22:05:37 [WARN] [vite] [plugin:vite-plugin-astro-expressive-code] context method
emitFile() is not supported in serve mode. This plugin is likely not vite-compatible.
```

Not sure if something changed in the Vite config, in Astro, or with the plugin, or which version this started appearing at.

**Comment by Creative-Difficulty** [comment]
@hippotastic @fflaten

**Comment by hippotastic** [comment]
Sorry for the lack of updates! I unfortunately have no time for OSS projects currently due to other work.

I assume this warning is a false positive and can be ignored. But if anybody is interested in researching and PRing a solution that fixes this or removes the warning, I'd be happy to review.

**Comment by evadecker** [comment]
@alexanderniebuhr Do you know how we might fix this? Looks like this commit is what added `emitFile()`: https://github.com/evadecker/expressive-code/commit/643d478660fdae4f0ce7359ae9db38ededd1d032

**Comment by alexanderniebuhr** [comment]
@evadecker I think the proper solution would be to outsource that feature to a new plugin which uses [apply: 'build'](https://vitejs.dev/guide/using-plugins.html#conditional-application) instead of the `command` condition. Not sure what the downsides to having multiple plugins are though 🤔

**Comment by hippotastic** [comment]
I'd have no issues with EC registering multiple Vite plugins as long as this is purely internal and doesn't increase complexity for the user.

**Comment by zellwk** [comment]
This is kinda problematic because I can't even build the site with the error :(

```bash
09:45:32 [WARN] [vite] [plugin:vite-plugin-astro-expressive-code] context method emitFile() is not supported in serve mode. This plugin is likely not vite-compatible.
✘ [ERROR] The build was canceled
```

**Comment by alexanderniebuhr** [comment]
I'm pretty sure the build doesn't break because of this warning. There should be another reason why it doesn't work.

**Comment by evadecker** [comment]
> @evadecker I think the proper solution would be to outsource that feature to a new plugin which uses [apply: 'build'](https://vitejs.dev/guide/using-plugins.html#conditional-application) instead of the `command` condition. Not sure what the downsides to having multiple plugins are though 🤷 
> 
> 
> 
> EDIT: I wonder why `astro check` uses the `build` command, but then tries to run `serve/dev` _(something to ask Erika maybe)_? 🤔 

[From Erika:](https://discord.com/channels/830184174198718474/845430950191038464/1265185666111770634)

> `astro check` doesn't do any of these things, it implicitly runs `astro sync`, which is what does that

**Comment by zellwk** [comment]
> I'm pretty sure the build doesn't break because of this warning. There should be another reason why it doesn't work.

Yeah you're right. Sorry about the misattribution. I found and fixed that offending error.

**Comment by hippotastic** [comment]
I just released a patch implementing your proposed solution (splitting the plugins and using `apply: build` for the one calling `emitFile`). It's now live on NPM as v0.35.5. Thanks everyone! 💜
