### ISSUE TITLE
Fails with shiki css variables theme

### ISSUE THREAD

**Issue by jcayzac** [expressive-code/expressive-code#225]
Expressive Code doesn't support Shiki's [CSS Variable Theme](https://shiki.matsu.io/guide/theme-colors#css-variables-theme).

```
Failed to resolve theme color for key editor.background: Invalid color value "var(--shiki-background)", expected a hex color.
  Stack trace:
    at …node_modules/@expressive-code/core/dist/index.js:3590:13
    at resolveVSCodeWorkbenchColors (…node_modules/@expressive-code/core/dist/index.js:3585:8)
```

**Comment by hippotastic** [comment]
This is by design. EC is all about accessibility and with the CSS variables theme, it's not possible to ensure proper color contrast with all the features.
