### ISSUE TITLE
Extending filetype support in comment-based filename detection

### ISSUE THREAD

**Issue by fflaten** [expressive-code/expressive-code#23]
Currently PowerShell-filenames are not detected from comments.

This works (shows tab with filename):
```powershell
# test.js
function Get-Demo {
```

This does not:
```powershell
# test.ps1 (or .psm1, .psd1)
function Get-Demo {
```

The same goes for `xml`, `csv` ++

Maybe add an option to let the user extend `LanguageGroups` with custom languages?
Or should we just provide PRs to extend the hardcoded list?

**Comment by hippotastic** [comment]
Welcome @fflaten, thank you for using Expressive Code and creating this issue!

I agree and have published a new version 0.16.0 to NPM that should fix the behavior you found. Changelog:

```md
- 07012f7: Improve file type support when extracting file names from comments. Thanks @fflaten!

  - Adds more file types to the `LanguageGroups` object
  - Exports `LanguageGroups` to allow external modification
  - Extends automatic detection of frame type to differentiate between
    shell scripts and terminal sessions based on file name and/or shebang (if any)
```

Please let me know if the new release fixes the issue for you.

Note that even before this release, it was always possible to set a file name or window title by adding the `title="your-file-name.ps1"` attribute after the opening code fence, so even if a file extension is not recognized by default in inline comments, you can still set it as a tab or window title this way.

However, now you can also add file extensions by importing `LanguageGroups` in your config file and modifying its contents to your liking, e.g. by pushing new extensions into any of the arrays.

**Comment by fflaten** [comment]
That was fast, thanks. Works great!

Should `LanguageGroups` stick to valid Shiki lang identifiers only? I see it's used both for lang-lookup and file extension-list atm. Might get bloated over time if this sets a precedence to include file-extensions.

If so I'm fine with dropping `psm1` and `psd1` from `terminal` group for now. Workarounds:
- `# .\file.psd1` since `powershell` is in terminal-group. Would require`.\` to be detected.
- `title="file.psd1"`

**Comment by hippotastic** [comment]
Glad to hear it works well!

You're right, the groups include some entries that are not valid Shiki languages.

However, as these are still common file extensions, I don't want to drop them. And due to their limited number, they don't seem to warrant creating a separate "file extension only" collection either, so I'm fine with grouping both together at the moment. Hope that makes sense. 😄

If we're continuing to expand this in the future and it becomes unwieldy at some point, we can of course revise this.
