### ISSUE TITLE
works in astro dev, but not after build

### ISSUE THREAD

**Issue by adamhl8** [expressive-code/expressive-code#258]
I'm having an issue where the new elements (such as `figure`) and styles are only appearing when my site is accessed from the astro dev server. After building and running `astro preview`, anything expressive-code related seems to be completely absent.

To be specific, after building, the `ec.{hash}.{js,css}` files are in the `dist/_astro/` directory, but none of my html files reference them at all.

I've tried setting `emitExternalStylesheet` to `false` but that didn't make a difference. 

I'm using astro `5.0.0-beta.5` so maybe something in v5 broke this integration? I don't see any errors or any indication that something is going wrong so I'm not sure if it's related.

If you'd like to reproduce the issue, it's on the `code` branch of my repo: https://github.com/adamhl8/adamhl.dev/tree/code

**Comment by hippotastic** [comment]
Thank you for the report. From your description, it sounds to me that EC doesn't even get to process your Markdown/MDX documents during build. Maybe something else is replacing code blocks with static HTML before EC gets a chance.

Have you tried commenting out your other remark & rehype plugins? I see that you have several in your config and these might be conflicting with EC.

You could also try setting `optimize: false` in the MDX integration options: https://docs.astro.build/en/guides/integrations-guide/mdx/#optimize

**Comment by adamhl8** [comment]
Apparently it was a combination of needing to delete my `.astro` folder and my minifier breaking some styles. It works now, thanks!
