### ISSUE TITLE
Windows drive letters missing from comment based title

### ISSUE THREAD

**Issue by fflaten** [expressive-code/expressive-code#26]
`# c:\temp\somefile` becomes `\temp\somefile` in title.

I'm not using this personally, but mentioned in case it was supposed to work. Feel free to close with workaround `title="c:\temp\somefile"`.

**Comment by hippotastic** [comment]
Good catch! I'll add a detection for Windows drive letters, it's definitely unexpected that they get cut off.

**Comment by hippotastic** [comment]
Should be fixed in 0.17.0! I just released it to NPM.
