### ISSUE TITLE
Extra code indentation required with <Code/> component

### ISSUE THREAD

**Issue by fviolette** [expressive-code/expressive-code#279]
Hello.

To produce this output with the latest Astro and Expressive Code versions:

```
dependencies:
  flutter:
    sdk: flutter

  contentsquare: ^3.14.159
 ```
 
I need to apply four indents as the first level of indentation (I won't do this 😁 ):
 
```
<Code lang="yaml" title="pubspec.yaml" code={`
dependencies:
    flutter:
      sdk: flutter

    contentsquare: ^${frontmatter.version}
`}/>
```

or apply a starting indent of two spaces:

```
<Code lang="yaml" title="pubspec.yaml" code={`
  dependencies:
    flutter:
      sdk: flutter

    contentsquare: ^${frontmatter.version}
`}/>
```

I was expecting the following to be the canonical way:

```
<Code lang="yaml" title="pubspec.yaml" code={`
dependencies:
  flutter:
    sdk: flutter

  contentsquare: ^${frontmatter.version}
`}/>
```

I'm suspecting a default trimming is applied to all lines which collapses the indent.
Side note, I can't import the snippets as code because the variables won't be resolved.

Is the behaviour I described expected?
Is there an option to implement in the EC config that would make the last example work?

Thanks.

**Comment by hippotastic** [comment]
Huh, that is strange! I've just tested this locally in an `.mdx` file on a Starlight site and the following code:

```mdx
import { Code } from '@astrojs/starlight/components'

<Code lang="yaml" title="pubspec.yaml" code={`
dependencies:
  flutter:
    sdk: flutter

  contentsquare: ^3.14.159
`}/>
```

Results in this output:

![image](https://github.com/user-attachments/assets/5a764b34-602e-47c3-ad12-02b81359184c)

Can you share more about the specific document & project you're using the `<Code>` component in? I assume the issue is not coming from the component itself, but rather how it's being used on the page.

**Comment by hippotastic** [comment]
As a side note, if it's only a few variables like `frontmatter.version` that you need to replace, you could make use of placeholders in an imported code snippet, or use regular expressions to find and inject the variables into the right places before passing it to the `code=...` prop.

But I'd rather find the true reason why something is stripping your indentation before it gets to the Code component of course! :)

**Comment by fviolette** [comment]
I'll double check. If that helps, my code component is auto-imported from `astro-expressive-code/components`.

From the astro config:

```
import { astroExpressiveCode, pluginFramesTexts } from "astro-expressive-code"

export default defineConfig({
...
integrations: [
  AutoImport({
    imports: [
      asideAutoImport,
      '~/components/tabs/Tabs.astro',
      '~/components/tabs/TabItem.astro',
      {
        'astro-expressive-code/components': ['Code'],
      }
    ],
  }),
  ...
})
```

**Comment by fviolette** [comment]
I also pulled the Starlight docs and inserted the following:

<img width="758" alt="Screenshot 2024-12-24 at 11 50 47" src="https://github.com/user-attachments/assets/5ada6bc7-fc22-46b8-b476-d0fa81bf1f26" />

<img width="808" alt="image" src="https://github.com/user-attachments/assets/c9552b76-2ec8-4f97-8b13-01627b4253d5" />

This rather points to an environment issue.

**Comment by fviolette** [comment]
See https://stackblitz.com/edit/github-un7eqm9c?file=src%2Fcontent%2Fdocs%2Findex.mdx for a reproduction

**Comment by hippotastic** [comment]
Thank you for the reproduction! I see the issue now, but I have to admit that I don't understand what is happening.

The following variation of the code works for me:

```mdx
export const code = `
dependencies:
  flutter:
    sdk: flutter

contentsquare: ^3.14.159
`;

<Code lang="yaml" title="pubspec.yaml" code={code}/>
```

While the other does not:

```mdx
<Code lang="yaml" title="pubspec.yaml" code={`
dependencies:
  flutter:
    sdk: flutter

contentsquare: ^3.14.159
`}/>
```

I assume this is some strange MDX / JSX indentation rule logic which processes the code before it even gets to Expressive Code. When I add a `console.log` statement to the `Code.astro` file powering the `<Code>` component to show what is contained in `Astro.props.code`, I can see that the indentation has already been stripped there. This does not happen when using a variable as I've shown above.

**Comment by hippotastic** [comment]
Yeah, it seems to be that code nested in JSX expressions is expected to be indented by one level. This works, too:

```mdx
<Code lang="yaml" title="pubspec.yaml" code={`
  dependencies:
    flutter:
      sdk: flutter

  contentsquare: ^3.14.159
`}/>
```

Notice that I also indented the `dependencies:` line in MDX in contrast to your example from the initial post. The resulting code looks as expected, and all lines have the correct indentation:

![image](https://github.com/user-attachments/assets/fa618ada-bb64-4633-8506-f7b7d1e9c144)

**Comment by fviolette** [comment]
Thanks for unpacking all of this.
By variable, I was actually referring to frontmatter keys and not const-s.

Then I'll make sure to explain this properly in our internal docs :-)

**Comment by hippotastic** [comment]
Sounds good!

I'm still wondering why this didn't happen in my first local test though. Maybe the expected indentation changed between Astro versions due to an update of the MDX integration?

**Comment by hippotastic** [comment]
For comparison, it was working for me locally with the following versions used by EC docs:

```
    "@astrojs/starlight": "^0.29.0",
    "astro": "^4.16.10",
```

Which versions did you test this on?

**Comment by hippotastic** [comment]
Update: I noticed that deleting my pnpm lockfile and reinstalling all packages also caused the new behavior to appear in EC docs. It seems that changes in upstream dependencies of Astro and/or Starlight are causing this. I'll keep investigating.

**Comment by hippotastic** [comment]
I spent almost an hour trying to find the problematic upstream package that is causing this change in behavior in Astro & Starlight, but unfortunately couldn't find it. I'm giving up as it's not EC's fault. If anyone happens to find the cause, please let me know!
