### ISSUE TITLE
[feature request] support ec.config.ts or ec.config.mts

### ISSUE THREAD

**Issue by sorawee** [expressive-code/expressive-code#283]
I have a plug-in written in TypeScript, so it cannot be imported from `ec.config.mjs`.

It would be nice to support the `.ts` extension, just like how the Astro config file supports both `.mjs` and `.ts`: https://docs.astro.build/en/guides/configuring-astro/#the-astro-config-file

**Comment by hippotastic** [comment]
Hello! This is only possible in Astro because Astro hosts a Vite instance that also allows it to parse a TypeScript config. As Expressive Code does not have a dependency on Vite, I'm afraid that it won't be possible to use the same way as Astro.

I'd recommend using a bundler like `tsup` to ensure that your plugin can also be imported and used from an MJS Astro config and EC config.

**Comment by sorawee** [comment]
Do you have any recommendation on how to develop a plugin in TypeScript? I attempted to use `tsup` as you suggested, but now I get errors like `Dynamic require of "path" is not supported`, which apparently occurs because of ["bundling CJS libraries into ESM context"](https://github.com/evanw/esbuild/issues/3324#issuecomment-1685217503). 

It's just unfortunate that using TypeScript requires things to be unnecessarily more complicated and difficult.

**Comment by hippotastic** [comment]
You can maybe have a look at my own default plugins which are all written in TypeScript. 

Here is one example: https://github.com/expressive-code/expressive-code/tree/main/packages/%40expressive-code/plugin-text-markers

As `tsup` tries to read as much information as possible from your project configuration, it's important that you have your `package.json` and `tsconfig.json` set up correctly. Then it's a matter of telling `tsup` what output you want, which I'm doing in the `package.json` script `build`.

Please note that my example unfortunately isn't as minimal as you'd probably prefer for learning - it is part of my monorepo where some shared dependencies including `tsup` itself are located in the [root package.json](https://github.com/expressive-code/expressive-code/blob/main/package.json), and most parts of the tsconfig are also inherited from the one in the root directory.

I hope that you can still take something from this example to reach your goal. If not, it might be a good idea to ask e.g. on the Astro Discord where a lot of knowledgeable and helpful people might be able to help. :)

**Comment by hippotastic** [comment]
Btw, I completely understand your frustration with the amount of extra work needed to develop in TypeScript. I honestly also fumbled my way through the tsup documentation and examples I found on the web to get to the point where I am now.

I'm happy that everything seems to work and I didn't get any complaints yet. 😅

**Comment by sorawee** [comment]
ESLint in particular relies on `jiti` (https://eslint.org/docs/latest/use/configure/configuration-files#typescript-configuration-files). But it's essentially a zero-effort setup. Users can choose to install the tool, and then it works.

**Comment by delucis** [comment]
While this is possible, packages like `jiti` tend to be really huge (1.7 MB in `jiti`’s case). I’m not sure installing nearly 2 MB of Node packages is worth it just to support a different config format.

Maybe once Node’s `--experimental-transform-types` flag and its built-in TypeScript support becomes stable it might be more viable to support this in the future.
