### ISSUE TITLE
Add support to pass `langAlias` to shiki 

### ISSUE THREAD

**Issue by mocusez** [expressive-code/expressive-code#284]
I noticed that Astro's shiki has supported `langAlias`: [Support Shiki's `langAlias` option in markdown configuration](https://github.com/withastro/roadmap/discussions/954)

I want to know whether this feature can also be added to [expressive-code](https://github.com/expressive-code/expressive-code), thank you

**Comment by hippotastic** [comment]
Hello! This is already being tracked in issue #278, so closing as a duplicate. Please subscribe to the other issue to get notified when this is available. :)

**Comment by hippotastic** [comment]
In case you didn't follow the other issue, I just wanted to let you know that I've released this feature to NPM in [version 0.39](https://expressive-code.com/releases/#0390).

Thanks again for the request! :)
