### ISSUE TITLE
Feature: Enhance `diff`

### ISSUE THREAD

**Issue by hirasso** [expressive-code/expressive-code#31]
I have found another topic that would be amazing to improve: `diff` highlighting and copying! 🥳

When rendering a `diff`, there are two chances for enhancements:

- The code could be highlighted if an additional language tag is being provided
- The "+" and "-" signs shouldn't be copied together with the source code when selecting the code for copying

This could be the syntax:

~~~
```diff lang="js"
- const foo = "foo";
+ const foo = "bar";
```
~~~

...which would still render nicely on GitHub:

```diff lang="js"
- const foo = "foo";
+ const foo = "bar";
```

There already is a [package that does this](https://github.com/GODLiangCY/markdown-it-shiki-extra/#readme), but it uses [non-standard syntax](https://github.com/GODLiangCY/markdown-it-shiki-extra/#colored-diffs) to achieve it's goal. Also, I'd love for `expressive-code` to become _the_ de facto standard for this kind of stuff :) 

You can see what that package renders on our deploy preview site:

https://deploy-preview-119--splendorous-kataifi-9ae281.netlify.app/getting-started/upgrading/

![image](https://github.com/expressive-code/expressive-code/assets/869813/7ff71d12-7c72-4701-9753-7dc4612076b8)

**Comment by hippotastic** [comment]
As you probably know, you can already do diff highlights in Expressive Code in any language right now by adding tags like `ins={3-5}` or `del={3-5}` to the opening code fence metadata. It's documented in the text markers plugin.

However, I really like the idea of supporting this for the `diff` language with a separate highlighting language!

Especially that this still shows the diff well on other platforms like GitHub is a big plus in my opinion.

Regarding the syntax, I could either imagine using your suggestion `'''diff lang="js"`, or a somewhat simpler `'''diff js` (imagine the `'`s were actual backticks).

**Comment by hippotastic** [comment]
@hirasso I just released version 0.19.0 to NPM that includes support for this feature. Please have a look and let me know if it works for you!

Here is the documentation: [Support for `diff`-like syntax](https://github.com/expressive-code/expressive-code/blob/main/packages/%40expressive-code/plugin-text-markers/README.md#support-for-diff-like-syntax)

**Comment by hirasso** [comment]
This is amazing @hippotastic ! I think now it's time to migrate our docs from `markdown-it` to `remark`, can't wait to use this!

**Comment by hirasso** [comment]
Works **like a charm** on my test site!

https://swup-fragment-plugin.netlify.app/how-it-works/ (at the very bottom)

![image](https://github.com/expressive-code/expressive-code/assets/869813/c75e6640-6aa8-46df-a288-1752df7a4a74)

**Comment by fflaten** [comment]
Love this, thanks to you both! So much easier while authoring and I immediately detected an example that was +1 off
