### ISSUE TITLE
TypeError: el.querySelectorAll is not a function

### ISSUE THREAD

**Issue by AkashRajpurohit** [expressive-code/expressive-code#33]
I am trying to integrate astro-expressive-code and noticed I am seeing these error logs on every page (even on pages where there are no code blocks)

<img width="617" alt="image" src="https://github.com/expressive-code/expressive-code/assets/30044630/bccb2a6b-967e-4781-bed6-59c65c3c9b7e">

I believe these are coming from here: https://github.com/expressive-code/expressive-code/blob/main/packages/%40expressive-code/plugin-frames/src/copy-js-module.ts#L98

Although the copy to code buttons seems to be working fine, but not sure why this error is popping up and how can I avoid it?

**Comment by hippotastic** [comment]
Hello, thank you for reporting this! Which browser are you using in which version?

Do you get the same error in other browsers as well?

**Comment by hippotastic** [comment]
Ohh, I have an idea! This error does not seem to happen during the initial search for buttons in the whole `document`, but in the `MutationObserver` that is triggered when new nodes get added to the page. My code was assuming that all those nodes support `querySelectorAll`, but there can be some node types where this is not true (e.g. text nodes).

I'll release a small fix ASAP that should hopefully solve this for you!

**Comment by hippotastic** [comment]
I just released the fix to NPM as version 0.18.1. Please update to the latest version and let me know if this solves the issue.

**Comment by AkashRajpurohit** [comment]
This works now, thanks for such a quick fix 🚀 🎉
