### ISSUE TITLE
Feature: highlight inline code expressions

### ISSUE THREAD

**Issue by kevinzunigacuellar** [expressive-code/expressive-code#40]
Would it be possible to for expressive-code to highlight inline code? I was thinking the syntax could look something like this. 
```
js`const a = foo`
```

**Comment by hippotastic** [comment]
One additional note: If we think that one of the primary use cases of inline code spans will be to reference code from a nearby code block, I could imagine doing what Code Hike does and applying the code same highlighting to spans as well. Maybe even without any underscores.

This would allow authors to automatically benefit from the highlighting in most cases without having to wrap any (potentially cumbersome) HTML tags around all inline code spans.

**Comment by kevinzunigacuellar** [comment]
Thank you for investigating @hippotastic. You have brought very good points with inline code highlight. One of the most pressing in my opinion would be "degrade gracefully". I like your first thought idea about introducing some data attributes to make the `<code>` highlightable. 

Since code highlight it's a very niche use case. I like the idea of adding some extra syntax to go the extra mile.
