### ISSUE TITLE
Feature: Exclude comments from certain languages when copying code

### ISSUE THREAD

**Issue by AkashRajpurohit** [expressive-code/expressive-code#41]
So the idea is that for certain language types like bash/shell if we could support excluding comments while copying then it makes those snippets more useful.

For example a snippet like this

```bash
# Install this amazing package via pnpm
pnpm install expressive-code
```

Will copy the comment as well and hence not very helpful to directly paste into terminal.

Discussed this first on [Astro discord channel](https://discord.com/channels/830184174198718474/872579324446928896/1136320887956721704).

**Comment by hippotastic** [comment]
Thank you for this feature idea, @AkashRajpurohit, and welcome here! I just released this to NPM as version 0.20.0. 😊
