### ISSUE TITLE
Shikiji support

### ISSUE THREAD

**Issue by AkashRajpurohit** [expressive-code/expressive-code#58]
Adding support for shikiji (currently shiki) will help users to use dual themes with expressive code

https://github.com/antfu/shikiji#lightdark-dual-themes

**Comment by hippotastic** [comment]
Hello Akash, thank you for this feature request!

I love the approach that Shikiji uses to support multiple themes. As Expressive Code is doing all the rendering itself already, it wouldn't benefit from using Shikiji as-is, but I'll use it as inspiration to add similar efficient multi-theme rendering.
