### ISSUE TITLE
Getting unwanted border with 0.23.0

### ISSUE THREAD

**Issue by fflaten** [expressive-code/expressive-code#61]
After upgrading to 0.23.0 I get a unwanted 1.5px border around codeblocks.

![image](https://github.com/expressive-code/expressive-code/assets/3436158/94dd3de7-457a-4d44-84b6-8b0b0a9de37e)

Caused by this:
![image](https://github.com/expressive-code/expressive-code/assets/3436158/9d91b5b9-cb34-43b6-b567-899bc687552f)

0.22.* or after unchecking the style above:
![image](https://github.com/expressive-code/expressive-code/assets/3436158/6cc51eba-f070-401a-b8a0-a99e7e425b22)

**Comment by fflaten** [comment]
Also this style when showing frame title:
![image](https://github.com/expressive-code/expressive-code/assets/3436158/512692ca-849d-43e9-b681-b84259e8ee4d)

**Comment by hippotastic** [comment]
Interesting! The border style itself has always been there, I wonder why the new version makes it more visible for you.

The only thing I changed is that there is another possible source for the `borderColor` style now. Which theme are you using?

**Comment by hippotastic** [comment]
Note that you can always use the config option `styleOverrides` to override any theme's border color with a color of your choice, or even remove it completely by setting it to `none`:

```js
// astro.config.mjs
import { defineConfig } from 'astro/config'
import astroExpressiveCode from 'astro-expressive-code'

export default defineConfig({
  integrations: [
    astroExpressiveCode({
      styleOverrides: {
        borderColor: 'none',
      },
    }),
  ],
})
```

**Comment by fflaten** [comment]
Using theme `nord`.

In 0.22.2 the border is `#454e60`

**Comment by fflaten** [comment]
Looks great - thanks for the quick fix! :)
The tabs look better also without the gap between tab and frame border
