### ISSUE TITLE
BUG: Click Handlers not working after View Transition in Astro

### ISSUE THREAD

**Issue by tanishqmanuja** [expressive-code/expressive-code#70]
In Astro 3.0 and above when view-transitions are enabled the click handlers are not re-applied after [page-swap](https://docs.astro.build/en/guides/view-transitions/#astroafter-swap). This breaks functionality like copy to clipboard provided by the frame plugin. I looked into this [file](https://github.com/expressive-code/expressive-code/blob/405a8ed9505b5b4cce8b2a69f0775f1c3f82aa55/packages/%40expressive-code/plugin-frames/src/copy-js-module.ts) but couldn't figure out what to patch.

**Comment by hippotastic** [comment]
Could you please share your `package.json`? 

I'm curious which version of `astro-expressive-code` you are using, because I introduced a MutationObserver a while back to prevent issues like this one.

If you're not using the latest version, maybe upgrading your dependencies might solve this issue.

**Comment by tanishqmanuja** [comment]
Here's the repo: https://github.com/tanishqmanuja/blog

**Comment by hippotastic** [comment]
Ok, thank you! I'll have a look. :)

**Comment by hippotastic** [comment]
Thanks again for sharing your reproduction repo. This was interesting! I would have expected the existing `MutationObserver` to trigger on view transitions, but apparently this isn't the case.

As I didn't find a generic browser-level "view transition finished" event to listen to, I added an Astro-specific `astro:page-load` event listener for now to solve the immediate issue.

I have just released the fix to NPM as version `0.26.1`. Please update your `astro-expressive-code` dependency to this latest version and let me know if this fixes the issue for you. I tested it locally on your repo and it worked for me.

**Comment by tanishqmanuja** [comment]
Works as expected!
Btw I had the same thought as you, putting something astro specific in the core package just feels odd as a developer idk why but it does. But until there is something more low level stuff we could do to figure out a transition end, this shouldn't interfere with other frameworks using remark as they wont emit astro:after-swap event.

Thanks again for such a speedy fix 🪄
