### ISSUE TITLE
Account for Starlight's manual dark-mode selection with `useDarkModeMediaQuery`

### ISSUE THREAD

**Issue by dbanty** [expressive-code/expressive-code#79]
With versions prior to 0.27.0, I was able to sync code block themes based on the theme selector in the upper right corner of Starlight sites using custom CSS. When updating [in this PR](https://github.com/knope-dev/knope/pull/653), this no longer works.

**Comment by hippotastic** [comment]
This is also already taken care of in my PR to add Expressive Code to Starlight. If you cannot wait (which I can totally understand of course :)), I'd advise you to have a look at the changes in the PR and copy over everything you need.

**Comment by hippotastic** [comment]
Here's a slightly modified excerpt taken from the PR that will fix this for you when you insert it into your config:

```js
/** @type {import('astro-expressive-code').AstroExpressiveCodeOptions} */
const expressiveCodeOptions = {
  // ...your other config options...
  themeCssSelector: (theme, { styleVariants }) => {
    // If one dark and one light theme are available,
    // generate theme CSS selectors compatible with Starlight's dark mode switch
    if (styleVariants.length >= 2) {
      const baseTheme = styleVariants[0]?.theme;
      const altTheme = styleVariants.find((v) => v.theme.type !== baseTheme?.type)?.theme;
      if (theme === baseTheme || theme === altTheme) return `[data-theme='${theme.type}']`;
    }
    // Return the default selector
    return `[data-theme='${theme.name}']`;
  },
};
```

**Comment by dbanty** [comment]
Thanks so much! I'll delay upgrading for a while and watch the Starlight PR, very cool to see this moving toward integration there!

**Comment by hippotastic** [comment]
Sounds good, although I didn't mean to discourage you from updating earlier! With the little excerpts I provided, everything should work on v0.27 as well. :)

Closing this for now as it's basically already solved in the PR.
