### ISSUE TITLE
styleOverrides.collapsibleSections types missing in 0.27.0

### ISSUE THREAD

**Issue by fflaten** [expressive-code/expressive-code#80]
`collapsibleSections` partial type is missing in `styleOverrides`.
Repro: https://stackblitz.com/edit/github-dqhp1q?file=astro.config.mjs

**Comment by fflaten** [comment]
Maybe the type is not merging properly because this plugin is external?

**Comment by hippotastic** [comment]
Well spotted! The issue was that module declaration didn't get picked up during build (it was missing from the generated type declaration file). I moved it to the `index.ts` file now and that seems to do the trick.

I'll release a patch in a moment. :)

**Comment by hippotastic** [comment]
The fix is live now as v0.27.1 on NPM. Thank you for the report and the reproduction!

**Comment by fflaten** [comment]
That was fast. Thanks 👏
