### ISSUE TITLE
Feature: Option to wrap text?

### ISSUE THREAD

**Issue by oofdere** [expressive-code/expressive-code#98]
## Problem

When copying output from a terminal, for instance, the text will copy unwrapped. even though it is wrapped in the terminal:

![image](https://github.com/expressive-code/expressive-code/assets/43102807/6efc1b0c-5807-4396-9ffd-2924a248a77d)

![image](https://github.com/expressive-code/expressive-code/assets/43102807/62d9cad9-74b6-495d-9362-52e2018e954e)

## Solution

There should be an option to wrap text. Maybe something like

````md
```bash wrap="true"
text goes here
```
````

**Comment by hippotastic** [comment]
Thank you for this feature request!

I agree, there should be a wrap option. I'll add it!

**Comment by endigo9740** [comment]
@hippotastic Hey I was just checking to see if this feature was implementing. Specifically for the `<Code />` component version, and ideally if there's a way to set this globally rather than per-instance.

**Comment by hippotastic** [comment]
What a coincidence, I'm actually working on this right now!

![image](https://github.com/expressive-code/expressive-code/assets/6137925/33a03872-8327-41b1-a87e-9e619f362327)

There is going to be a release in the next couple of days that includes line numbers, word wrapping and custom gutter icon support. Everything is going to be configurable as always. :)

**Comment by endigo9740** [comment]
Oh awesome, this will be super valuable. Thank you so much! I'll keep an eye out for this release.

**Comment by hippotastic** [comment]
This feature is now available in the new 0.33 minor release. You can find the docs here: https://expressive-code.com/key-features/word-wrap/

It's configurable both globally in the EC config, and per block using the meta string or per Code component using props.

This will also be available in Starlight once my PR to update to my latest release got merged. This is planned for Friday. Hope that helps! :)

**Comment by endigo9740** [comment]
Thank you @hippotastic! This is a great a11y improvement! Very excited to implement!
